# 连接端口号
server:
  port: 8083


# 数据库连接
spring:
  jackson:
    time-zone : GMT+8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/microblog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

# redis配置
shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379

# 扫描*Mapper.xml文件
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 配置Jwt
microblog:
  jwt:
      # 加密密钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
      # token 的有效时长：7天，单位是秒
    expire: 604800
    header: Authorization
